version: "3.9"

services:
  api:
    build: .
    container_name: churn-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONPATH=/app/src
    command: uvicorn churn_mlops.api.main:app --host 0.0.0.0 --port 8000

  mlflow:
    image: python:3.11-slim
    container_name: churn-mlflow
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: bash -lc "pip install --no-cache-dir mlflow==2.16.2 && mlflow ui --backend-store-uri /app/mlruns --host 0.0.0.0 --port 5000"
